GET http://localhost:8080/api/cars/1/maintenances/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg3ODM2NDQ2LCJleHAiOjE3ODc4NDAwNDZ9.mXd4gv8U3XaJkQ7zyCo0SnIa0rNzaVQiK2KoNbhSkjR4IPIoOAeqNiMHuOG5Muly