spring.datasource.url=jdbc:postgresql://localhost:5432/healthcar
spring.datasource.username=healthcar
spring.datasource.password=healthcar
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

logging.level.org.springframework.security=DEBUG