GET http://localhost:8080/api/cars?page=0&size=20&sort=id,desc
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg3ODQxMjAyLCJleHAiOjE3ODc4NDQ4MDJ9.PykCmeMoh9Bx7HesnNbN6SW_NrnOddSJb96_q-nWV04dK5HUCZblJwB3LP7Xrvpf