PUT http://localhost:8080/api/cars/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg3NzU0MDgwLCJleHAiOjE3ODc3NTc2ODB9._oZH2ADpjhk_NeBOQUjLmrdqYd9u0J2_9Ri7PHqxDHh3FlhM7HgHD_ULFQqH0t2w

{
  "maker": "MAZDA",
  "carModel": "MAZDA2",
  "modelYear": 2019,
  "description": "メインカー",
  "odometer": 95000,
  "status": 0,
  "imageUrl": "https://example.com/images/MAZDA2.jpg"
}