GET http://localhost:8080/api/cars/1/customs/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg3NDEwMzkzLCJleHAiOjE3ODc0MTM5OTN9.9KbafjTsPcZk4yivC4VwghSRMAUMt1GWk74JG3RLBLzxIswWKYTN4QY5Jo-v8ofu