GET http://localhost:8080/api/cars/1/customs/1
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzg3ODM5Mjc2LCJleHAiOjE3ODc4NDI4NzZ9.BZDrBGxFt0aDl8mMo0_exqDJWzpSqGFSytAzgZ-gQJDz98VjiRKQIsYA06am4lx4